packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  esbuild: true
  msgpackr-extract: true
  unrs-resolver: set this to true or false
onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract
overrides:
  esbuild: '>=0.28.1'
