#!/usr/bin/env bash
#
# gen-notes.sh — generate the first draft of a NiteOwl release notes file.
#
# Walks the merged commits since the previous release tag, buckets them by
# Conventional Commit type into the sections defined in docs/release-process.md
# §5, and routes anything that touched packages/ee-* into a dedicated
# Commercial (ee-*) section so the open-core / commercial line is preserved.
#
# This produces a DRAFT: the Release Manager edits it for clarity and user
# impact before publishing (see docs/release-process.md §6 step 4).
#
# Usage:
#   scripts/release/gen-notes.sh [SINCE_REF]
#
#   SINCE_REF   Previous release tag/ref to diff from (e.g. v0.1.0).
#               Omit it for the very first release to cover all history.
#
# Examples:
#   scripts/release/gen-notes.sh v0.1.0 > notes.md     # since the last tag
#   scripts/release/gen-notes.sh > notes.md            # first release (all history)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
cd "${REPO_ROOT}"

SINCE_REF="${1:-}"
if [ -n "${SINCE_REF}" ]; then
  if ! git rev-parse --verify --quiet "${SINCE_REF}^{commit}" >/dev/null; then
    echo "gen-notes: ref '${SINCE_REF}' not found." >&2
    exit 1
  fi
  RANGE="${SINCE_REF}..HEAD"
  SINCE_LABEL="${SINCE_REF}"
else
  RANGE="HEAD"
  SINCE_LABEL="(inception)"
fi

TODAY="$(date +%Y-%m-%d)"

# Accumulators, one bullet per line.
features=""; improvements=""; fixes=""; commercial=""; maintenance=""

# Walk commits newest-first. %H<TAB>%s gives hash + subject (PR-squash subjects
# carry the Conventional Commit prefix and the "(#NN)" PR ref).
while IFS=$'\t' read -r hash subject; do
  [ -z "${hash}" ] && continue

  # Does this commit touch commercial code? If so it belongs in Commercial,
  # regardless of its conventional type — the licence boundary wins.
  if git diff-tree --no-commit-id --name-only -r "${hash}" \
       | grep -q '^packages/ee-'; then
    commercial+="- ${subject}"$'\n'
    continue
  fi

  case "${subject}" in
    feat:*|feat\(*) features+="- ${subject}"$'\n' ;;
    fix:*|fix\(*)   fixes+="- ${subject}"$'\n' ;;
    perf:*|perf\(*|refactor:*|refactor\(*)
                    improvements+="- ${subject}"$'\n' ;;
    chore:*|chore\(*|ci:*|ci\(*|test:*|test\(*|docs:*|docs\(*)
                    maintenance+="- ${subject}"$'\n' ;;
    *)              maintenance+="- ${subject}"$'\n' ;;
  esac
done < <(git log --no-merges --pretty=format:'%H%x09%s' "${RANGE}")

section() { # $1 = heading, $2 = body — print only if body non-empty
  if [ -n "${2}" ]; then
    printf '## %s\n\n%s\n' "${1}" "${2}"
  fi
}

cat <<EOF
# NiteOwl vX.Y.Z — ${TODAY}

<!-- DRAFT generated by scripts/release/gen-notes.sh from ${SINCE_LABEL}..HEAD.
     Edit for clarity and user impact, set the version, then publish.
     See docs/release-process.md §5–§6. -->

EOF

section "New features" "${features}"
section "Improvements" "${improvements}"
section "Bug fixes" "${fixes}"
section "Commercial (ee-*)" "${commercial}"
section "Maintenance" "${maintenance}"

if [ -z "${features}${improvements}${fixes}${commercial}${maintenance}" ]; then
  echo "_Maintenance only — no user-visible changes this release._"
fi
